services:
  api:
    container_name: rewindj-api
    image: ghcr.io/guilhermeguedes1/rewindj-api:latest
    command: yarn start:prod
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      NODE_ENV: production
    restart: unless-stopped
