version: '3'

services:
  api:
    container_name: orbit-api

    build: .

    ports:
      - '3000:3000'

    volumes:
      - .:/app

    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    container_name: orbit-db
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=orbit
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
