import { Controller, Post, Get, UseGuards, Body, Param } from '@nestjs/common';
import { InvitesService } from './invites.service';
import { AuthGuard } from '../auth/auth.guards';
import { CurrentUser } from 'src/auth/decorators/user.decorator';
import { CurrentUserDto } from '../auth/dtos/user.dto';
import { CreateInviteDto } from './dtos/create-invite.dto';
import { AcceptInviteDto } from './dtos/accept-invite.dto';
import {
  ApiBearerAuth,
  ApiBadRequestResponse,
  ApiBody,
  ApiConflictResponse,
  ApiCreatedResponse,
  ApiExtraModels,
  ApiNotFoundResponse,
  ApiOkResponse,
  ApiOperation,
  ApiParam,
  ApiTags,
  ApiUnauthorizedResponse,
} from '@nestjs/swagger';
import {
  AcceptInviteResponseDto,
  CreateInviteResponseDto,
  InviteByTokenResponseDto,
  InviteStatusDocumentationDto,
} from './dtos/invite-response.dto';

@ApiTags('Invites')
@ApiExtraModels(InviteStatusDocumentationDto)
@Controller('invites')
export class InvitesController {
  constructor(private readonly invitesService: InvitesService) {}

  @ApiBearerAuth()
  @ApiOperation({
    summary: 'Create an invitation for a new organization member',
    description:
      'Creates a short-lived invite token for the authenticated organization. The invite determines the role assigned when the recipient accepts it.',
  })
  @ApiBody({ type: CreateInviteDto })
  @ApiCreatedResponse({
    description: 'Creates an invite and returns the invite link.',
    type: CreateInviteResponseDto,
  })
  @ApiBadRequestResponse({ description: 'Request body failed validation.' })
  @ApiUnauthorizedResponse({
    description: 'Missing or invalid bearer token.',
  })
  @UseGuards(AuthGuard)
  @Post()
  createInvite(
    @CurrentUser() user: CurrentUserDto,
    @Body() body: CreateInviteDto,
  ) {
    return this.invitesService.createInvite(user, body);
  }

  @ApiOperation({
    summary: 'Get invite details by token',
    description:
      'Public endpoint used before acceptance to validate an invite token and display the organization and role associated with it.',
  })
  @ApiParam({
    name: 'token',
    description: 'Invite token generated by the create invite endpoint.',
    example: '2cb6b88f-2f29-4f57-9565-b403e0f2f973',
  })
  @ApiOkResponse({
    description: 'Returns the invite information for the token.',
    type: InviteByTokenResponseDto,
  })
  @ApiBadRequestResponse({
    description: 'Invite is expired or no longer pending.',
  })
  @ApiNotFoundResponse({ description: 'Invite token was not found.' })
  @Get(':token')
  findByToken(@Param('token') token: string) {
    return this.invitesService.findByToken(token);
  }

  @ApiOperation({
    summary: 'Accept an invite token',
    description:
      'Public endpoint that creates a user inside the invited organization. Artist invites also create the linked artist profile.',
  })
  @ApiParam({
    name: 'token',
    description: 'Invite token generated by the create invite endpoint.',
    example: '2cb6b88f-2f29-4f57-9565-b403e0f2f973',
  })
  @ApiBody({ type: AcceptInviteDto })
  @ApiCreatedResponse({
    description: 'Accepts the invite and creates the user.',
    type: AcceptInviteResponseDto,
  })
  @ApiBadRequestResponse({
    description:
      'Invite is expired, no longer pending, or body validation failed.',
  })
  @ApiNotFoundResponse({ description: 'Invite token was not found.' })
  @ApiConflictResponse({
    description: 'A user with the invite email or phone already exists.',
  })
  @Post(':token/accept')
  acceptInvite(@Param('token') token: string, @Body() body: AcceptInviteDto) {
    return this.invitesService.accept(token, body);
  }
}
